management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  boot:
    client:
      url: http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.3.164:3306/databaseforexp2?serverTimezone=GMT%2B8
    username: mybaby
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 300
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100

      validation-query: select 1

  sql:
    init:
      encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.example.exp_5.model
  mapper-locations: classpath:com.example.exp_5.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 172.16.1.149:9876
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2


rocketmqdemo:
  order-topic:
    # 固定的延时等级 "1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h"
    delay-level: 3
    #超时时间（秒）
    timeout: 10
