# Generated by Django 4.0.2 on 2022-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, verbose_name='用户名')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='WeiboData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_username', models.CharField(max_length=32, verbose_name='博主昵称')),
                ('weibo_verification', models.CharField(default='未认证', max_length=32, null='True', verbose_name='微博认证')),
                ('weibo_content', models.TextField(verbose_name='微博内容')),
                ('submit_time', models.TextField(verbose_name='发布时间')),
                ('forward_counts', models.IntegerField(default=0, verbose_name='转发数')),
                ('comments_counts', models.IntegerField(default=0, verbose_name='评论数')),
                ('points_times', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
    ]
